// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/EditorialSkincareDashboard-Ef1Gcu/App.tsx": () => import("../components/mockups/templates/EditorialSkincareDashboard-Ef1Gcu/App.tsx"),
  "./components/mockups/templates/ModernBankingDashboard-HEf2fy/VaultBanking.tsx": () => import("../components/mockups/templates/ModernBankingDashboard-HEf2fy/VaultBanking.tsx"),
  "./components/mockups/templates/RetroKidsLearningBrochure-p9u0rL/App.tsx": () => import("../components/mockups/templates/RetroKidsLearningBrochure-p9u0rL/App.tsx")
};
